app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Basic Text Summarizer
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/siliconflow:0.0.33@6792acf632f24f1c41a3192a78ef181f7149811a8dfd9a16ade984978613f79c
    version: null
kind: app
version: 0.4.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: llm
      id: 1761900523911-source-1761900581239-target
      source: '1761900523911'
      sourceHandle: source
      target: '1761900581239'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: end
      id: 1761900581239-source-1761900592455-target
      source: '1761900581239'
      sourceHandle: source
      target: '1761900592455'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        selected: false
        title: 开始
        type: start
        variables:
        - default: ''
          hint: ''
          label: text
          max_length: 2000
          options: []
          placeholder: ''
          required: true
          type: paragraph
          variable: text
      height: 88
      id: '1761900523911'
      position:
        x: 228
        y: 263
      positionAbsolute:
        x: 228
        y: 263
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        context:
          enabled: true
          variable_selector:
          - '1761900523911'
          - text
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: deepseek-ai/DeepSeek-R1
          provider: langgenius/siliconflow/siliconflow
        prompt_template:
        - id: 818ea194-7162-4e11-b9e4-4bd5302935ef
          role: system
          text: Please provide a concise summary of {{#1761900523911.text#}}
        selected: false
        structured_output_enabled: true
        title: LLM
        type: llm
        vision:
          enabled: false
      height: 88
      id: '1761900581239'
      position:
        x: 560
        y: 276
      positionAbsolute:
        x: 560
        y: 276
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        outputs:
        - value_selector:
          - '1761900581239'
          - text
          value_type: string
          variable: summary
        selected: false
        title: 结束
        type: end
      height: 88
      id: '1761900592455'
      position:
        x: 908
        y: 276
      positionAbsolute:
        x: 908
        y: 276
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    viewport:
      x: -41.02526765978564
      y: 12.021603680798307
      zoom: 0.8570418149165003
  rag_pipeline_variables: []
